### ISSUE TITLE
Support loopback.cfg

### ISSUE THREAD

**Issue by probonopd** [acritox/kanotix#1]
Please support [`loopback.cfg`](https://www.supergrubdisk.org/wiki/Loopback.cfg) so that tools like [SystemImageKit](https://github.com/probonopd/SystemImageKit) can boot KANOTIX without hassle. Thanks!

**Comment by retabell** [comment]
This is done in
https://github.com/acritox/kanotix/commit/a1f4c276bc9f2b8083691aa1a58ccbb38e93cf68

**Comment by probonopd** [comment]
Thanks @retabell
